package demo.models;

import javax.validation.constraints.NotNull;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Created by tewe on 12/7/2016.
 */

@Entity
@Table(name = "faqs")
public class Faq {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The user's question
    @NotNull
    private String question;

    // The user's answer
    @NotNull
    private String category;
    @NotNull
    private String answer;
    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Faq() { }

    public Faq(long id) {
        this.id = id;
    }

    public Faq(String question, String category, String answer)
    {
        this.question = question;
        this.answer = answer;
        this.category =category;
    }

    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String value) {
        this.question = value;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String value) {
        this.answer = value;
    }


    @Override
    public String toString() {
        return String.format("[id = %s, question = %s, category = %s, answer=%s]", id, question, category,answer);
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void initTestData(){
        this.setId(1);
        this.setQuestion("vad är det");
        this.setCategory("cat1");
        this.setAnswer("det kommer");
    }
}
