package demo.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * An entity User composed by three fields (id, email, username).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the username for the table in the db.
 *
 * @author Tewelle
 */
@Entity
@Table(name = "users")
public class User {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's email
  @NotNull
  private String email;
  
  // The user's username
  @NotNull
  private String name;
  @NotNull
  private String username;
  @NotNull
  private String password;

  @NotNull
  private Date updateDate;

  @NotNull
  private Date creationDate;
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String email, String username, String password) {
    this.email = email;
    this.username = username;
    this.password =password;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getUsername() {
    return username;
  }

  public void setUsername(String value) {
    this.username = value;
  }


  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public void update(String username, String email,String name, String password)
  {
    this.username = username;
    this.name = name;
    this.email = email;
    this.password =password;
  }

  @PreUpdate
  public void preUpdate() {
    updateDate = new Date();
  }

  @PrePersist
  public void prePersist() {
    Date now = new Date();
    creationDate =now;
    updateDate = now;
  }

  /*@Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this);
  }*/

  @Override
  public String toString() {
    return String.format("[id = %s, username = %s, email = %s, password=%s]", id, username, email,password);
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Date getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  public Date getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }
}
